<a href="https://colab.research.google.com/github/DiegoRodrigues1402/Notebooks_Colab/blob/main/descricao_alunos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
url ='https://raw.githubusercontent.com/alura-cursos/pandas-conhecendo-a-biblioteca/main/desafios/alunos.csv'
dados = pd.read_csv(url,sep=',')
dados.head()

    Nome  Idade  Notas  Aprovado
0    Ary     20    7.5      True
1    Ana     18    NaN     False
2  Cátia     27    2.5     False
3  Denis     18    5.0     False
4   Beto     21   10.0      True

In [ ]:
dados["Pontos_extras"] = dados['Notas'] * 40 / 100
dados.head()

    Nome  Idade  Notas  Aprovado  Pontos_extras
0    Ary     20    7.5      True            3.0
1    Ana     18    NaN     False            NaN
2  Cátia     27    2.5     False            1.0
3  Denis     18    5.0     False            2.0
4   Beto     21   10.0      True            4.0

In [ ]:
dados['Notas_finais'] = dados['Notas'] + dados['Pontos_extras']
dados.head()

    Nome  Idade  Notas  Aprovado  Pontos_extras  Notas_finais
0    Ary     20    7.5      True            3.0          10.5
1    Ana     18    NaN     False            NaN           NaN
2  Cátia     27    2.5     False            1.0           3.5
3  Denis     18    5.0     False            2.0           7.0
4   Beto     21   10.0      True            4.0          14.0

In [ ]:
dados['Aprovado_final'] = dados['Notas_finais'].apply(lambda x :"Aprovado" if x >= 6 else 'Reprovado')
dados.head(18)

,Nome,Idade,Notas,Aprovado,Pontos_extras,Notas_finais,Aprovado_final
0,Ary,20,7.5,True,3.00,10.50,Aprovado
1,Ana,18,NaN,False,NaN,NaN,Reprovado
2,Cátia,27,2.5,False,1.00,3.50,Reprovado
3,Denis,18,5.0,False,2.00,7.00,Aprovado
4,Beto,21,10.0,True,4.00,14.00,Aprovado
5,Bruna,23,NaN,False,NaN,NaN,Reprovado
6,Dara,21,7.0,True,2.80,9.80,Aprovado
7,Carlos,19,6.0,True,2.40,8.40,Aprovado
8,Alice,35,5.6,False,2.24,7.84,Aprovado
9,Vitor,28,NaN,False,NaN,NaN,Reprovado
10,Daniel,21,NaN,False,NaN,NaN,Reprovado
11,Igor,24,4.5,False,1.80,6.30,Aprovado
12,Sthefanie,26,9.5,True,3.80,13.30,Aprovado
13,Mirla,25,9.0,True,3.60,12.60,Aprovado
14,Paulo,37,NaN,False,NaN,NaN,Reprovado
15,Mylena,29,7.0,True,2.80,9.80,Aprovado
16,Lucas,33,NaN,False,NaN,NaN,Reprovado
17,Nadia,34,8.0,True,3.20,11.20,Aprovado

In [ ]:
antigos_reprovados = dados.query('Aprovado == False')
antigos_reprovados

      Nome  Idade  Notas  Aprovado  Pontos_extras  Notas_finais Aprovado_final
1      Ana     18    NaN     False            NaN           NaN      Reprovado
2    Cátia     27    2.5     False           1.00          3.50      Reprovado
3    Denis     18    5.0     False           2.00          7.00       Aprovado
5    Bruna     23    NaN     False            NaN           NaN      Reprovado
8    Alice     35    5.6     False           2.24          7.84       Aprovado
9    Vitor     28    NaN     False            NaN           NaN      Reprovado
10  Daniel     21    NaN     False            NaN           NaN      Reprovado
11    Igor     24    4.5     False           1.80          6.30       Aprovado
14   Paulo     37    NaN     False            NaN           NaN      Reprovado
16   Lucas     33    NaN     False            NaN           NaN      Reprovado